<a href="https://colab.research.google.com/github/vitoriapmaattos/dataanalytics/blob/main/Fase__1_Estat%C3%ADstica_e_%C3%81lgebra_Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Algebra Linear:

x+ 2 = 5 -> x = 3

Resolver sistemas de equações lineares

In [ ]:
import numpy as np #mais famosa para lidar com números matemáticos
import scipy as sc #segunda opção
import sympy as sy #outra opção mas entrega a saida em equação - simbolos matemáticos

In [ ]:
#escalar -> é um número (tensor de ordem 0)
x = 2
#vetor
x2 = np.array([1 ,2 ,3]) #um vetor com 3 elementos escalares
#matriz
x3 = np.array([[1],[2],[3]]) #uma matriz com 3 vetores cada um com 1 elemento escalar
#matriz tradicional
x4 = np.array([[1 ,2 ,3],[1 ,2 ,3],[1 ,2 ,3]])

In [ ]:
print(x2)
print()
print(x3)
print()
print(x4)

[1 2 3]

[[1]
 [2]
 [3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import pandas as pd

In [ ]:
lista = np.array([1, 2, 3, 4, 5])

df = pd.DataFrame({'coluna 1':lista,'coluna 2':lista})

In [ ]:
df

coluna 1  coluna 2
0         1         1
1         2         2
2         3         3
3         4         4
4         5         5

In [ ]:
x2

array([1, 2, 3])

In [ ]:
x3

array([[1],
       [2],
       [3]])

In [ ]:
x4

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
x3+x4

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])