<a href="https://colab.research.google.com/github/vitoriapmaattos/dataanalytics/blob/main/Fase3_Aula5_Sistemas_de_Recomendacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Modelo de Recomendação Simples**

In [2]:
#Importando as bibliotecas estatisticas

import scipy
from scipy import stats
import numpy as np

In [6]:

#Cria uma matriz com as notas dos filmes dadas por 3 usuários
matrix = np.array([[8,0,3,4,6],[5,6,1,8,9],[8,0,0,5,10]])

#Notas dos filmes para um novo usuário
novoUser = [8,0,2,3,0]

#Indica os filmes que o novo usuário não assistiu (0 para não assistido, 1 para assistido)
nao_assistidos = [0,1,0,0,1]

#Imprime a matriz de notas
print(matrix)

#Lista com os nomes dos filmes, correspondendo às colunas da matriz
nomeFilmes = ['Round 6', 'A Invocação do Mal', '9 Desconhecidos', 'You', 'La Casa de Papel']

[[ 8  0  3  4  6]
 [ 5  6  1  8  9]
 [ 8  0  0  5 10]]


In [8]:
# Inicializa o vetor de similaridade com zeros para 3 usuários
similarity = [0] * 3

# Imprime alguns elementos da matriz para ilustrar
print(matrix[0][0])  # Nota do primeiro usuário para o primeiro filme
print(matrix[1][0])  # Nota do segundo usuário para o primeiro filme
print(matrix[1,:])   # Notas de todos os filmes do segundo usuário

# Para cada usuário na matriz...
for i in range(0,3):
    # Extrai as notas do usuário atual
    temp = matrix[i,:]

    print(i, temp) #Imprime o índice do usuário e suas notas

    #Filtra as notas do usuário apenas para os filmes que o novo usuário assistiu
    tempUser = [ t for n,t in zip(novoUser,temp) if n != 0 ]

    #Filtra as notas do novo usuário para os filmes que ele assistiu
    tempNovoUser = [n for n in novoUser if n != 0]

    #Verificação das notas usadas na comparação
    print('user:', i)
    print(tempUser, tempNovoUser)

    #Calcula a similaridade entre o novo usuário e o usuário atual usando o coeficiente de Pearson
    similarity[i] = scipy.stats.pearsonr(tempUser,tempNovoUser)[0] #O primeiro valor retornado é o coeficiente de Pearson

# Imprime as similaridades calculadas
print()
print(similarity)

8
5
[5 6 1 8 9]
0 [8 0 3 4 6]
user: 0
[8, 3, 4] [8, 2, 3]
1 [5 6 1 8 9]
user: 1
[5, 1, 8] [8, 2, 3]
2 [ 8  0  0  5 10]
user: 2
[8, 0, 5] [8, 2, 3]

[0.9994237971287663, 0.23621543814299698, 0.8723686098443353]


In [11]:
#Dando peso para as notas dadas ao filme

nota_peso = np.zeros((3,5)) #Cria uma matriz de zeros com 3 linhas (usuários) e 5 colunas (filmes) para armazenar as notas ponderadas

for nUser in range(3): # Loop sobre cada usuário na matriz (3 usuários)
  for nFilme in range(5): # Loop sobre cada filme (5 filmes)
    #Exibe a estrutura da equação que será usada para calcular a nota ponderada, com placeholders
    print('nota_peso[',nUser, '][',nFilme, '] = , nao_assistidos[',nFilme, '], * ,matrix[',nUser,'][',nFilme, '], * similarity[',nUser,']')

    # Exibe a equação real com os valores atuais
    print('nota_peso[',nUser, '][',nFilme, '] = ', nao_assistidos[nFilme], ' * ' ,matrix[nUser][nFilme], ' * ', similarity[nUser])

    #Calcula a nota ponderada para o filme atual considerando se o novo usuário não assistiu,
    #A nota dada pelo usuário atual, e a similaridade entre o usuário atual e o novo usuário
    nota_peso[nUser][nFilme] = nao_assistidos[nFilme] * matrix[nUser][nFilme] * similarity[nUser]

#Exibe a matriz final com as notas ponderadas para cada filme e cada usuário
print(nota_peso)

nota_peso[ 0 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 0 ][ 0 ], * similarity[ 0 ]
nota_peso[ 0 ][ 0 ] =  0  *  8  *  0.9994237971287663
nota_peso[ 0 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 0 ][ 1 ], * similarity[ 0 ]
nota_peso[ 0 ][ 1 ] =  1  *  0  *  0.9994237971287663
nota_peso[ 0 ][ 2 ] = , nao_assistidos[ 2 ], * ,matrix[ 0 ][ 2 ], * similarity[ 0 ]
nota_peso[ 0 ][ 2 ] =  0  *  3  *  0.9994237971287663
nota_peso[ 0 ][ 3 ] = , nao_assistidos[ 3 ], * ,matrix[ 0 ][ 3 ], * similarity[ 0 ]
nota_peso[ 0 ][ 3 ] =  0  *  4  *  0.9994237971287663
nota_peso[ 0 ][ 4 ] = , nao_assistidos[ 4 ], * ,matrix[ 0 ][ 4 ], * similarity[ 0 ]
nota_peso[ 0 ][ 4 ] =  1  *  6  *  0.9994237971287663
nota_peso[ 1 ][ 0 ] = , nao_assistidos[ 0 ], * ,matrix[ 1 ][ 0 ], * similarity[ 1 ]
nota_peso[ 1 ][ 0 ] =  0  *  5  *  0.23621543814299698
nota_peso[ 1 ][ 1 ] = , nao_assistidos[ 1 ], * ,matrix[ 1 ][ 1 ], * similarity[ 1 ]
nota_peso[ 1 ][ 1 ] =  1  *  6  *  0.23621543814299698
nota_peso[ 1 ][ 2 ] = , nao_assi

In [12]:
#Somando as notas com os pesos
notas_acumuladas = np.sum(nota_peso.T,axis=1)
print(notas_acumuladas) #Exibe as notas acumuladas para cada filme

[ 0.          1.41729263  0.          0.         16.84616782]


In [13]:
temp_peso = nota_peso #Cria uma cópia da matriz nota_peso (inicialmente, ambas apontam para a mesma matriz)
temp_peso[nota_peso > 0] = 1 #Substitui todos os valores de temp_peso maiores que 0 por 1
print(temp_peso) #Exibe a matriz temp_peso após a modificação


temp_similaridade = np.zeros((3,5)) #Cria uma matriz de zeros 3x5 para armazenar a similaridade ponderada
for nUser in range(3): #Itera sobre os 3 usuários
  for nFilme in range(5): #Itera sobre os 5 filmes

    #Calcula a similaridade ponderada para cada filme e usuário, considerando se o filme foi recomendado
    temp_similaridade[nUser][nFilme] = temp_peso[nUser][nFilme] * similarity[nUser]

print(temp_similaridade) #Exibe a matriz temp_similaridade com as similaridades ponderadas

similaridade_acumulada = np.sum(temp_similaridade.T,axis=1) #Calcula a soma acumulada das similaridades para cada filme (somando as colunas da transposta)
print(similaridade_acumulada) #Exibe a similaridade acumulada para cada filme

[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
[[0.         0.         0.         0.         0.9994238 ]
 [0.         0.23621544 0.         0.         0.23621544]
 [0.         0.         0.         0.         0.87236861]]
[0.         0.23621544 0.         0.         2.10800785]


In [14]:
nota_final = [0] * 5  #Inicializa uma lista de tamanho 5 com zeros, que armazenará a nota final normalizada para cada filme

#Normalização das notas acumuladas para cada filme
for nFilme in range(5):  #Itera sobre os 5 filmes
    if(similaridade_acumulada[nFilme] > 0):  #Verifica se a similaridade acumulada para o filme é maior que 0
        #Se a similaridade acumulada for maior que 0, normaliza a nota acumulada dividindo pela similaridade acumulada
        nota_final[nFilme] = notas_acumuladas[nFilme] / similaridade_acumulada[nFilme]
    else:
        #Se a similaridade acumulada for 0 (ou não houver recomendação relevante), define a nota final como 0
        nota_final[nFilme] = 0

print(nota_final)  #Exibe a lista nota_final, que contém as notas normalizadas para cada filme

[0, 6.0, 0, 0, 7.991510972567143]


In [16]:
nAssistidos = sum(nao_assistidos)  #Calcula o número de filmes que o novo usuário ainda não assistiu (soma os valores em nao_assistidos)

#Ordena os índices dos filmes com base nas notas finais em ordem decrescente
notasOrdenadasIndex = sorted(range(len(nota_final)), key=nota_final.__getitem__)[::-1][0:nAssistidos]
print(notasOrdenadasIndex)  #Exibe os índices dos filmes ordenados pelas notas finais, dos melhores para os piores

#Imprime os nomes dos filmes recomendados junto com suas notas finais
for i in notasOrdenadasIndex:
    print(nomeFilmes[i], '- Nota: ', nota_final[i])  #Exibe o nome do filme e a nota final correspondente


[4, 1]
La Casa de Papel - Nota:  7.991510972567143
A Invocação do Mal - Nota:  6.0
